### ISSUE TITLE
Sort the teams drop-down

### ISSUE THREAD

**Issue by dd32** [WordPress/meeting-calendar#126]
As reported on Trac by @tobifjellner https://meta.trac.wordpress.org/ticket/5897
> The "Teams" drop-down on make.wordpress.org/meetings currently hosts 17 teams.
> In order to make ie easier to find the team you want to filter for, I suggest that the items in this list should be sorted alphabetically.

![meetings-teams-dropdown](https://user-images.githubusercontent.com/767313/146131449-9b58f05b-647f-443c-a214-87ae63bdaf7d.png)

**Comment by PhakphumV** [comment]
Hello, 
After restart my docker compose, the issue has been resolved.
I added an enhancement but failed at php unit test "MeetingAPITest::test_meeting_third_wednesday"

I tested without changes I made and still got the same result too. 
Could it be because there is something wrong with this test case? Or did I miss anything?
